### ISSUE TITLE
validobj is not compatible with python 3.8

### ISSUE THREAD

**Issue by scarlehoff** [Zaharid/validobj#7]
Since it uses `typing.Annotated` (https://github.com/Zaharid/validobj/blob/d118641ce6ff6ff0559752960ec9fa98430a2884/validobj/custom.py#L10) which was introduced in 3.9: https://docs.python.org/3.9/library/typing.html#typing.Annotated

**Comment by Zaharid** [comment]
I am not sure what to do about this other than documenting it better (I thought it was).

**Comment by Zaharid** [comment]
I have added the relevant clarifications in the places I can think of.

**Comment by scarlehoff** [comment]
Might be also useful to add a try-except on the `custom.py` import of Annotated so that the user get a message telling them what it went wrong. Other than that suggestion this can be considered closed from my side.
